# general settings
name: self_guided_sr_x2_aapm
model_type: SelfGuidanceModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
scale: 2

# dataset and data loader settings
datasets:
  train_b30:
    name: aapm_b30_train_full
    type: PairedSelfGuidanceDataset
    dataroot_gt: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/fd/train_full/hr
    dataroot_lq: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/train_full/x2
    dataroot_avg_coronal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/train_full_avg/x2/avg_coronal
    dataroot_avg_sagittal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/train_full_avg/x2/avg_sagittal
    dataroot_avg_axial: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/train_full_avg/x2/avg_axial

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  train_d45:
    name: aapm_d45_train_full
    type: PairedSelfGuidanceDataset
    dataroot_gt: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/fd/train_full/hr
    dataroot_lq: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/train_full/x2
    dataroot_avg_coronal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/train_full_avg/x2/avg_coronal
    dataroot_avg_sagittal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/train_full_avg/x2/avg_sagittal
    dataroot_avg_axial: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/train_full_avg/x2/avg_axial

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_b30:
    name: aapm_b30_val
    type: PairedSelfGuidanceDataset
    dataroot_gt: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/fd/val/hr
    dataroot_lq: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/val/x2
    dataroot_avg_coronal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/val_avg/x2/avg_coronal
    dataroot_avg_sagittal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/val_avg/x2/avg_sagittal
    dataroot_avg_axial: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_B30/qd/val_avg/x2/avg_axial
    io_backend:
      type: disk

  val_d45:
    name: aapm_d45_val
    type: PairedSelfGuidanceDataset
    dataroot_gt: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/fd/val/hr
    dataroot_lq: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/val/x2
    dataroot_avg_coronal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/val_avg/x2/avg_coronal
    dataroot_avg_sagittal: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/val_avg/x2/avg_sagittal
    dataroot_avg_axial: /data/zhiyi/data/aapm_1mm_slice_window_-1000_200/1mm_D45/qd/val_avg/x2/avg_axial
    io_backend:
      type: disk

# network structures
network_g:
  type: SelfGuidanceSR
  upscale: 2
  in_channel: 1
  out_channel: 1
  img_size: 48
  patch_size: 1
  num_feat: 180
  depths: [ 6, 6, 6, 6, 6, 6 ]
  num_heads: [ 6, 6, 6, 6, 6, 6 ]
  window_size: 8
  mlp_ratio: 2.
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.1
  resi_connection: '1conv'

network_pde:
  type: PriorDegradationEstimator

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

  pretrain_network_degradation_estimator: /home/zhiyi/code/basicsr-neu/experiments/pde/models/net_g_latest.pth

# training settings
train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 400000]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false
  pbar: true
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
